### ISSUE TITLE
Issue / Question: ext-header-ids

### ISSUE THREAD

**Issue by jrmiller82** [kivikakk/comrak#126]
Assuming `ComrakOptions { ext_header_ids: Some("bar".to_string()) }`,  and assuming input markdown of `# Home` why does the anchor link `href="#home"` not equal the id parameter which ends up being `id="barhome"`? 

What's the point of the anchor link not matching the id? Should the anchor link be matching the id? Maybe I don't do enough front-end dev and I'm just not familiar with that convention, but I don't see the point of having an anchor link that points to a non-existent id, making the anchor link do nothing (yes, I know it's aria=hidden but I don't understand *why*).

Thanks in advance.

Edit: `ComrakOptions { ext_header_ids: Some("".to_string()) }` will set the anchor link and the id to be the same if that means anything.

**Comment by kivikakk** [comment]
The function of the option is to do exactly that: prefix IDs to facilitate namespacing in the document. This is for GitHub compatibility: anchors are prefixed with `user-content-`, but the anchor _targets_ are unchanged so that you still see `#home` in the address bar and not `#user-content-home`. We use JavaScript to look up the `user-content-`-prefixed ID.

If you just want free anchor generation, you can use an empty prefix as you've shown.

**Comment by jrmiller82** [comment]
Thank you for the explanation.
