### ISSUE TITLE
markdown_to_html contains unwrap()

### ISSUE THREAD

**Issue by Boscop** [kivikakk/comrak#131]
I think it would be good if `markdown_to_html` wouldn't unwrap but return a Result instead.
(Because I'm using it server-side and I don't want my server thread to panic because of this.)

**Comment by kivikakk** [comment]
It would be a bug if that `unwrap` panicked; there should only be UTF-8 characters entering that buffer. If you want to insulate against the chance of such a bug, I suggest you reimplement the body of `markdown_to_html` in your code, but in short, the `unwrap` *should* remain — there should be no input that causes it to panic. I don't want to expose a `Result` because it would suggest that there might be a valid case where an error was returned.

**Comment by Boscop** [comment]
Ok, makes sense. But then, why is the AST storing `Vec<u8>` instead of `String`s?

**Comment by kivikakk** [comment]
See https://github.com/kivikakk/comrak/pull/38 — using `String`s ends up with a lot of re-asserting UTF-8 validity, even when the inputs are all guaranteed to be UTF-8 valid (because they themselves are `str`s). So we manipulate raw byte buffers internally and then do one last sanity check, just in case, but that check will only fail if there's an actual bug.
