### ISSUE TITLE
0.8.2 was semver-major-breaking release

### ISSUE THREAD

**Issue by kornelski** [kivikakk/comrak#167]
c70d51b63061e7b4f77571d2990ae70c861b7fc8 has added a new option. The option structs are public, so any time you add or change any of the options, you're making a major breaking change.

**Comment by kivikakk** [comment]
Thanks for the heads up. Will fix this tonight and get some CI going to alert me to these in future so I stop making the same mistakes.

**Comment by kivikakk** [comment]
I might skip on the yank this time unless you feel strongly about this. My reading of semver is the API for major version 0 can change at any time.

**Comment by coolaj86** [comment]
@kivikakk In general the "de facto" rule is that:
1. Anything that's gained enough traction to go into production systems gets bumped to `v1.0.0`. Many projects are doing a 10x bump in order to get rid of the "v1" stigma. In this case Comrak would become `v8.3.0`.
2. If you're not following rule #1, then the "minor" version as treated as if it were "major" such that `v0.9.0` is a breaking change from `v0.8.1`.

There's no RFC for that, but it seems to be good netiquette and I think comrak would benefit from following either of these conventions.

**Comment by kornelski** [comment]
Personally, I'm OK with keeping the existing releases, since I've already updated code on my side. Just going forward, please keep in mind that changes to exposed structs can break builds, so either bump semver or maybe use a builder pattern.

As for semver saying 0.* is completely unstable, that's technically correct for the semver spec, but behavior of Cargo and Rust ecosystem doesn't interpret it like that. In version `0.m.p` cargo treats `m` as semver-major bump, and `p` as compatible releases. 

Rust ecosystem has many 0.x libraries that are in fact pretty stable (even the most popular one: libc 0.2), so 0.x isn't a clear sign of instability.

**Comment by kivikakk** [comment]
Thanks, I will do. A builder pattern isn't a bad idea; for now I've implemented tests that will break when the public API changes like this, to alert me to it in future.

**Comment by kornelski** [comment]
0.9.1 broke semver again. ab976a7885be794e52420d622973320b70a8ddd6

**Comment by kivikakk** [comment]
Ugh, thanks. I missed it because the PR author (kindly) added the test. Added an entry to my checklist to check for changes to that test before releases. I'm going to add the builder pattern now.
