### ISSUE TITLE
Don't expose type_arena

### ISSUE THREAD

**Issue by ivanceras** [kivikakk/comrak#17]
In the example:
```rust
let arena = Arena::new();

let root = parse_document(
    &arena,
    "This is my input.\n\n1. Also my input.\n2. Certainly my input.\n",
    &ComrakOptions::default());
```
type_arena is exposed, but not really manipulated by the library user. Shouldn't be there a function which instantiate a default arena object on itself while still be able to do the advance features like search replace. Library users can then just use something like

```rust
let root = parse_document_default_arena(
    "This is my input.\n\n1. Also my input.\n2. Certainly my input.\n",
    &ComrakOptions::default());
```

**Comment by kivikakk** [comment]
Unfortunately, that's not possible given the current design; the signature of `parse_document` is as follows:

``` rust
fn parse_document<'a>(arena: &'a Arena<AstNode<'a>>,
                      buffer: &str,
                      options: &ComrakOptions)
                      -> &'a AstNode<'a>
```

The returned node is parameterised by `'a`, and the reference's lifetime is bound by `'a`, which is supplied in the input by the `Arena`.  What signature would `parse_document_default_arena` have?

``` rust
fn parse_document_default_arena<'a>(buffer: &str,
                                    options: &ComrakOptions)
                                    -> &'a AstNode<'a>
```

This type signature is invalid because `'a` needs to be supplied in the input somehow. It's not possible to have a static global arena (again: whence does the lifetime argument come from?), and at any rate, it means it would be impossible to deallocate memory.

I don't see a very easy way to do this, unfortunately, unless you have any ideas! 😞

**Comment by ivanceras** [comment]
Oh, it seems complicated than I thought.
