### ISSUE TITLE
Support for grid layout tables - Feedback wanted.

### ISSUE THREAD

**Issue by coolaj86** [kivikakk/comrak#180]
# In Short

Would you be open to a PR that allows an option like `--tables=grid-components` to output tables as something like `<mkdn-grid>` or `<div class="mkdn-grid">` rather than `<table>`?

# Rationale

I was talking with a friend of mine who is strong in the ways of CSS (cc/ @uniqname) about how to make a modern stylesheet for a Markdown blog template for students and he lamented the use of `<table>` due to how it is **_difficult to style on mobile_**.

I'm imagining that it wouldn't be too hard for someone like myself to create an option to swap out table rendering with grid rendering.

**Comment by kivikakk** [comment]
I am a bit loathe to add such an option to comrak directly --- its purpose is to produce CommonMark/GFM-compliant HTML output, and [tables have a specified format](https://github.github.com/gfm/#tables-extension-). I think this kind of change would be best performed by a filter (i.e. one that parses the HTML output and replaces `<table>` nodes with whatever suits the user's styling desires best, as they are all likely to differ depending on their CSS choices) or a program that used Comrak as a library and formatted the AST nodes itself.

Otherwise we run the risk of trying to suit everyone's needs and becoming a bit of an undirected mess; I would rather the library stay small and support a culture of many different other programs using it than trying to do everything in one.
