### ISSUE TITLE
What is happening inside handle_backslash?

### ISSUE THREAD

**Issue by vedantroy** [kivikakk/comrak#188]
Hi! Thanks for making this library.

I'm curious as to what is happening inside `handle_backslash`, here:

https://github.com/kivikakk/comrak/blob/79391a5ac23ac609bcb702da1d0faa1aed5f7caa/src/parser/inlines.rs#L812

**Comment by vedantroy** [comment]
A follow-up is, what is happening inside `parse_code_block_prefix`? (I'm trying to add my own type that is similar to a fenced code block).

https://github.com/kivikakk/comrak/blob/79391a5ac23ac609bcb702da1d0faa1aed5f7caa/src/parser/mod.rs#L1015

- I'm guessing `if !fenced` checks whether the code block is fenced or indented
- I'm not sure what `matched` stands for

Not sure what is happening

here:
```rust
        if matched >= fence_length {
            *should_continue = false;
            self.advance_offset(line, matched, false);
            self.current = self.finalize_borrowed(container, ast).unwrap();
            return false;
        }
```

or here:

```rust
        let mut i = fence_offset;
        while i > 0 && strings::is_space_or_tab(line[self.offset]) {
            self.advance_offset(line, 1, true);
            i -= 1;
        }
        true
```

**Comment by kivikakk** [comment]
Hiya, @vedantroy! These are patterned exactly from the source code in the reference C implementation. See:

https://github.com/commonmark/cmark/blob/8a023286198a7e408398e282f293e3b0baebb644/src/inlines.c#L796-L797

In essence, we check if the next character is punctuation. If it is, we move the inline parser past that character, and create a text node just for that character we skipped. This means `\"` will get turned into just `"`. If not, if we're on a line end, add a regular line break (what happens when you put a lone `\` at EOL). If none of those, return an actual text node containing a `\` character. This means `\a` will get rendered as `\a`, i.e. the escape won't get "consumed". See [this part of the spec](https://spec.commonmark.org/0.29/#backslash-escapes) where it says "Backslashes before other characters are treated as literal backslashes".

https://github.com/commonmark/cmark/blob/8a023286198a7e408398e282f293e3b0baebb644/src/blocks.c#L814-L855

Check the C implementation here. There's a bit more commenting there and it might make more sense in the original context. It's going to be nearly impossible to explain it deeply without explaining how the entire parser works, but to answer your specific questions:

If `matched >= fence_length` means there were at least as many backticks (or tildes) scanned as there were that opened it. i.e. if this was a code block that opened with three backticks, then we matched at least 3. That means the code block is being closed.

The loop you're asking about just optionally skips whitespace characters, up to the offset of the indentation of the initial fence. So if you have a fenced code block that starts on character 6 in the line, then up to 6 spaces are trimmed from the start of each line in the code block. e.g. one that starts mid-list like this:

````markdown
  ```
  <- these two spaces get trimmed off
but leaving them out entirely is okay
  ```
````

Renders like this:

  ```
  <- these two spaces get trimmed off
but leaving them out entirely is okay
  ```

**Comment by vedantroy** [comment]
Hi! Thanks for the response. I managed to fork Comrak to get a parser that supported LaTeX environment syntax (`\begin{envname} ... \end{endname}` working as well as a few other goodies!

I appreciate the large amount of detail, it made this a lot easier. Thanks for taking the time!

**Comment by kivikakk** [comment]
Awesome work, great to hear! Glad I could help. :heart:
