### ISSUE TITLE
<number>. don't render as table td. 

### ISSUE THREAD

**Issue by ivanceras** [kivikakk/comrak#19]
I've notice that this renders badly
```
Number | Tag | Description
-------|-----|---------
1.     | CC  | Coordinating conjunction
2.     | CD  | Cardinal number
3.     | DT  | Determiner
4.     | EX  | Existential there
```
as 
Number | Tag | Description
-------|-----|---------
1.     | CC  | Coordinating conjunction
2.     | CD  | Cardinal number
3.     | DT  | Determiner
4.     | EX  | Existential there
And it's not unique to comrak, but to gfm as well as the render take effect in this github issue

If you remove the `.`  right after the numbers, it renders fine.
```
Number | Tag | Description
-------|-----|---------
1     | CC  | Coordinating conjunction
2     | CD  | Cardinal number
3     | DT  | Determiner
4     | EX  | Existential there
```
Number | Tag | Description
-------|-----|---------
1     | CC  | Coordinating conjunction
2     | CD  | Cardinal number
3     | DT  | Determiner
4     | EX  | Existential there

pulldown-cmark renders both nicely. Is this an intended behaviour in gfm specification?

**Comment by kivikakk** [comment]
:wave: Thanks for the report! It looks like the table extension doesn't get to fire before the ordered list parser, causing this strange result.

comrak is pretty much a straight copy of the GitHub cmark-gfm code, which is why they render the same, so I guess technically this is an issue with cmark-gfm. I'll try to fix this first in [github/cmark](https://github.com/github/cmark), and then copy the fix across here.

**Comment by kivikakk** [comment]
(Note that, as a work around, you can include a leading `|`)

**Comment by kivikakk** [comment]
I've reviewed the code and the spec a bit, and it looks like this probably isn't something we can "fix" without actually altering the spec (which I'm loathe to do). See [here](https://github.github.com/gfm/#example-191):

> The table is broken at the first empty line, or beginning of another block-level structure:
>
> ``` markdown
> | abc | def |
> | --- | --- |
> | bar | baz |
> > bar
> ```
>
> | abc | def |
> | --- | --- |
> | bar | baz |
> > bar

In order to preserve logical parsing precedence rules, it'd be pretty difficult to have that last line interpreted as part of the table if and only if there was a pipe (`|`) character located somewhere in it.

pulldown-cmark's parsing strategy for tables differs quite a bit, which is why this "works" there, but without breaking examples like the above (and/or big hacks), I don't think we'll be able to achieve this in GFM.

So, I think the solution will be to prefix the table with pipes:

``` markdown
| Number | Tag | Description
| -------|-----|---------
| 1.     | CC  | Coordinating conjunction
| 2.     | CD  | Cardinal number
| 3.     | DT  | Determiner
| 4.     | EX  | Existential there
```

Producing:

| Number | Tag | Description
| -------|-----|---------
| 1.     | CC  | Coordinating conjunction
| 2.     | CD  | Cardinal number
| 3.     | DT  | Determiner
| 4.     | EX  | Existential there
