### ISSUE TITLE
&str instead of &[char] ?

### ISSUE THREAD

**Issue by ConnyOnny** [kivikakk/comrak#2]
There is this public function:

```rust
pub fn parse_document<'a>(arena: &'a Arena<Node<'a, RefCell<Ast>>>,
                          buffer: &[char],
                          options: &ComrakOptions)
                          -> &'a Node<'a, RefCell<Ast>>
```

Why do you use `&[char]` for the buffer? Isn't converting a regular `String` to that type very costly because every character will be forced to use 4 bytes? Why do you not use `&str` instead?

**Comment by kivikakk** [comment]
:wave: Heya, thanks for opening the issue!

In general I haven't nailed down (a) performance targets, or (b) the general design yet. Right now I'm operating on `Vec<char>` and `&[char]` because it means almost all Unicode issues are dealt with without any effort on my behalf.

Once I get all the GFM specs passing in #1 and merged, I'll be starting to benchmark and fix big issues like this one!

**Comment by kivikakk** [comment]
Done! Thank you for the report! :heart:
