### ISSUE TITLE
Autolink combined with escaping prevents some links from being automatically linked

### ISSUE THREAD

**Issue by maplant** [kivikakk/comrak#207]
Attempting to parse this text:
```
https://www.youtube.com/
<div>test</div> 
https://www.youtube.com/
```
with the following options:
```rust
        options.extension.strikethrough = true;
        options.extension.table = true;
        options.extension.autolink = true;
        options.extension.tasklist = true;
        options.render.hardbreaks = true;
        options.render.escape = true;
        options.parse.smart = true;
```
Leads to the following output:

```
<p><a href="https://www.youtube.com/">https://www.youtube.com/</a></p>
&lt;div&gt;test&lt;/div&gt; 
https://www.youtube.com/
```
I would expect the second youtube link to also be linked, but it is not.

**Comment by kivikakk** [comment]
Hi there; this is per spec. No Markdown is being interpreted at all past the `<div>`; see a similar issue here https://github.com/kivikakk/comrak/issues/185#issuecomment-821909480.

**Comment by maplant** [comment]
@kivikakk no dispute here, but I guess I thought because hardbreaks was set to true that would add the newline necessary to parse the link? I'll just disable hardbreaks and double the newlines :-) Thanks for the quick response!

**Comment by kivikakk** [comment]
No probs! And ah yeah, that makes sense! I never considered that way of thinking about it, probably because as an implementer my head's too in the details: the hardbreaks option doesn't actually change parsing behaviour at all! It's an option that has its effect strictly at the rendering stage; see [§ 6.8 Soft line breaks](https://spec.commonmark.org/0.30/#soft-line-breaks). `hardbreaks` relates to that last sentence:

> A renderer may also provide an option to render soft line breaks as hard line breaks.

Thanks for the issue! Much prefer possible issues would be reported than not :)

**Comment by maplant** [comment]
That explains why the option was in the render section! I get it now, thanks!
