### ISSUE TITLE
Parity: Autolink works incorrectly with links inside wiki style link

### ISSUE THREAD

**Issue by digitalmoksha** [kivikakk/comrak#296]
Given the example

```
- [[linked-resource]]
- [[link-text|linked-resource]]
- [[http://example.com]]
- [[link-text|http://example.com/pdfs/gollum.pdf]]
- [[images/example.jpg]]
- [[http://example.com/images/example.jpg]]
```

comrak generates

```
<ul>
<li>[[linked-resource]]</li>
<li>[[link-text|linked-resource]]</li>
<li>[[<a href="http://example.com%5D%5D">http://example.com]]</a></li>
<li>[[link-text|<a href="http://example.com/pdfs/gollum.pdf%5D%5D">http://example.com/pdfs/gollum.pdf]]</a></li>
<li>[[images/example.jpg]]</li>
<li>[[<a href="http://example.com/images/example.jpg%5D%5D">http://example.com/images/example.jpg]]</a></li>
</ul>
```

Notice how the auto linking is incorrectly recognizing the links.

**Comment by digitalmoksha** [comment]
For comparison with other parsers.  All except `cmark-gfm` properly recognize the boundary of the link, leaving the `[[` and `]]` intact. `cmark-gfm` don't recognize them as links at all.

**cmark-gfm**

```
<ul>
<li>[[linked-resource]]</li>
<li>[[link-text|linked-resource]]</li>
<li>[[http://example.com]]</li>
<li>[[link-text|http://example.com/pdfs/gollum.pdf]]</li>
<li>[[images/example.jpg]]</li>
<li>[[http://example.com/images/example.jpg]]</li>
</ul>
```

**markdown-rs**

```
<ul>
<li>[[linked-resource]]</li>
<li>[[link-text|linked-resource]]</li>
<li>[[<a href="http://example.com">http://example.com</a>]]</li>
<li>[[link-text|<a href="http://example.com/pdfs/gollum.pdf">http://example.com/pdfs/gollum.pdf</a>]]</li>
<li>[[images/example.jpg]]</li>
<li>[[<a href="http://example.com/images/example.jpg">http://example.com/images/example.jpg</a>]]</li>
</ul>
```

**markdown-it.rs**

```
<ul>
<li>[[linked-resource]]</li>
<li>[[link-text|linked-resource]]</li>
<li>[[<a href="http://example.com">example.com</a>]]</li>
<li>[[link-text|<a href="http://example.com/pdfs/gollum.pdf">example.com/pdfs/gollum.pdf</a>]]</li>
<li>[[images/example.jpg]]</li>
<li>[[<a href="http://example.com/images/example.jpg">example.com/images/example.jpg</a>]]</li>
</ul>
```

**commonmark-hs**

```
<ul>
<li>[[linked-resource]]</li>
<li>[[link-text|linked-resource]]</li>
<li>[[<a href="http://example.com">http://example.com</a>]]</li>
<li>[[link-text|<a href="http://example.com/pdfs/gollum.pdf">http://example.com/pdfs/gollum.pdf</a>]]</li>
<li>[[images/example.jpg]]</li>
<li>[[<a href="http://example.com/images/example.jpg">http://example.com/images/example.jpg</a>]]</li>
</ul>
```

**Comment by digitalmoksha** [comment]
I'm not sure which is exactly the _correct_ way.  Coming from `cmark-gfm`, that is the output we expect (and operate on).  However it seems more correct how the other parsers handle it, and consistent across them.

**Comment by kivikakk** [comment]
Interesting! I do think the other parsers' handling here is better, though I'd probably prefer to keep Comrak in line with cmark-gfm. Some reconciling with its autolink extension is in order.

**Comment by digitalmoksha** [comment]
@kivikakk I wanted to ask you about how to move forward.

It seems that in general, from what I can tell, `comrak` is a (mostly) straight port of `cmark-gfm` to Rust.  Meaning same code structure, function names, and logic.  What I like to call bug-for-bug compatible.

I've done similar ports before, from JS to Ruby. The only way I was able to keep it updated in a sane fashion was to diff the changes of the original repo between two releases, and then make the corresponding changes in the ported repo. Even if I was multiple releases behind, I took it release by release in order to keep things consistent and working.

I'm not sure if you've been doing something like this or not, or how far behind it might be - which `cmark-gfm` release the current code is based on.

There have definitely been some changes to `autolink` that should be incorporated, as well as other rendering differences in the very latest release.

What do you think the best way forward is? Just diff the older `autolink.c` with the latest and try to apply those changes?  Walk through each release like I mentioned above?  Or just fix what ever seems to be broken based on the most recent specs?  And I don't know if all the security patches have been applied.

🤔

**Comment by kivikakk** [comment]
> Meaning same code structure, function names, and logic. What I like to call bug-for-bug compatible.
> 
> I've done similar ports before, from JS to Ruby. The only way I was able to keep it updated in a sane fashion was to diff the changes of the original repo between two releases, and then make the corresponding changes in the ported repo. Even if I was multiple releases behind, I took it release by release in order to keep things consistent and working.

This is indeed, essentially what I've done, and it has been an explicit design goal from the start. (See [§ Related projects](https://github.com/kivikakk/comrak/blob/a87860c653d12336a8a556ee4615cb74a9126acf/README.md#related-projects) in the README.)

Similarly, when there have been some big changes that I've needed to match, I've likewise basically analysed every change in `cmark-gfm` and then replicated it in Comrak.

This most recently happened with these two security advisories:

* https://github.com/kivikakk/comrak/security/advisories/GHSA-8hqf-xjwp-p67v
* https://github.com/kivikakk/comrak/security/advisories/GHSA-xxmq-4vph-956w

These were both fixed in upstream `cmark-gfm`, and ~90% of them were a straight port to Comrak specifically because it was written this way.

(The major issue specific to Comrak that was brought up at the same time was that some of our quadratic parsing issues were specific to our use of [pest](https://github.com/pest-parser/pest), which is a fantastic library, but not well-suited for the way I was using it. https://github.com/kivikakk/comrak/commit/ce795b7f471b01589f842dc09af38b025701178d fixed the quadratic issues, including swapping out pest for [re2c](https://re2c.org/).)

Since all those changes, we're a lot closer to upstream than we were. I do not actively track it — I don't use Comrak myself, nor do I have any ongoing sponsor to do so. GitHub did disclose these vulnerabilities to me along with a bunch of helpful reproduction cases, and so I made the most of that opportunity to do that work back in March/April. They donated some money after I completed that work, which I appreciate.

> There have definitely been some changes to `autolink` that should be incorporated, as well as other rendering differences in the very latest release.

Indeed; autolink actually never really diverged. For reasons I can't remember, I implemented it differently in Comrak to begin with. (I did the initial `cmark-gfm` implementation, too, so perhaps I just thought I knew better.) It's probably because the way we postprocess inlines is slightly different. I had to take some pains to port security issues more recently (https://github.com/kivikakk/comrak/commit/f61e8bbb763382027a6bc12cb9bb9f099929749c) because of this difference. It would be nicer if they matched, but I haven't looked into how much work it would be to bring them in line.

> What do you think the best way forward is? Just diff the older `autolink.c` with the latest and try to apply those changes?

I think so!

> And I don't know if all the security patches have been applied.

At least as of April, I think we're pretty close. I can't say for sure.

**Comment by digitalmoksha** [comment]
I went through and compared each release. It looks like we're pretty up to date with `0.29.0.gfm.2`. And many of the changes in the following releases have been incorporated, but it looks like a handful are missing.

So if it's ok with you, I will tackle each release, and add a relevant PR for any changes needed. By the end of it, we should be able to say we're compliant with `0.29.0.gfm.11`, and mark it in the README. I think that would allow us to more easily upgrade to new releases as they come out.

wdyt?

**Comment by kivikakk** [comment]
I'm more than happy to review this work, yes!

**Comment by digitalmoksha** [comment]
This was fixed by https://github.com/kivikakk/comrak/pull/325
