### ISSUE TITLE
Should parsing a markdown file and rendering it back to markdown preserve the state?

### ISSUE THREAD

**Issue by pacak** [kivikakk/comrak#336]
Currently blocks like 

```
[`foo`]
```

are turned into

```
\[`foo`\]
```

**Comment by kivikakk** [comment]
The answer to your question is no; in round-tripping to CommonMark the precise formatting may be modified so long as the AST it produces is the same as the input, and there is no guarantee that otherwise would happen. (I'd further expect it to be stable: `input | comrak -t commonmark` should be equal to `input | comrak -t commonmark | comrak -t commonmark`.)

You can always implement your own CommonMark output formatter for the AST instead if you want to do better, or indeed, submit a PR to improve the supplied one — see [`comrak::cm::outc`](https://github.com/kivikakk/comrak/blob/72b5209405e6177ff04577013daa7febd70fe615/src/cm.rs#L185-L240). Our current behaviour mimics upstream's.
