### ISSUE TITLE
Rendering of hard line breaks

### ISSUE THREAD

**Issue by jneem** [kivikakk/comrak#372]
`cmark-gfm` renders hard line breaks as two spaces followed by a newline. Since #214, `comrak` renders hard line breaks as a backslash followed by a newline. This change makes it a bit tricky to build up `comrak` ASTs programmatically, because if you put a hard line break at the end of a block it will get rendered as a backslash in the markdown. And then because commonmark specifies that a backslash at the end of a block is treated as a literal backslash instead of a line break, you will get a backslash in the output.

I tried to make a PR to change this behavior, but every option has some problems. Here are some possibilities:

1. Keep the current behavior, and require anyone constructing their own AST to be careful about inserting line breaks. This is doable, but tricky to do correctly. (For anyone running into a similar issue, our [workaround](https://github.com/tweag/nickel/pull/1880) was to use paragraph nodes instead of line breaks.)
2. Revert to the `cmark-gfm` behavior. This has the advantage of sticking close to upstream, but the disadvantage that hard line breaks at the beginning of a block no longer round-trip. This lack of a round-trip is how cmark-gfm currently behaves:
    ```
    $ echo '> \\n> a' | cmark-gfm -t commonmark test2.md | hexdump -C
    00000000  3e 20 20 20 0a 3e 20 61  0a                       |>   .> a.|
    $ echo '> \\n> a' | cmark-gfm -t commonmark test2.md | cmark-gfm -t commonmark | hexdump -C
    00000000  3e 20 61 0a                                       |> a.|
    ```
3. Make `NodeValue::LineBreak` have two variants (space-space or backslash). Downstream users get to choose which one they want. The parser remembers which one was used, and re-renders it when outputting commonmark.

What do you think? I prefer option 3, but if you're really serious about being bug-for-bug compatible with cmark-gfm then maybe 2 is better :shrug:

(Edit: I'd be happy to make a PR for either option 2 or 3. Obviously option 1 doesn't require any changes...)

**Comment by kivikakk** [comment]
Just briefly my own preference here: I slightly prefer option 2 over 1, since if we're going to have a bug, I'd rather it was at least compatible with upstream than divergent, but no bug at all would be even better — documents of all sorts should roundtrip.

I'm not sure how much I love modifying the AST per option 3, but I think it's still clearly better than 1 or 2. It introduces some difficulties because it requires users constructing an AST from scratch to choose, and choosing incorrectly could inadvertently introduce a backslash into their document (!) when they thought they were adding a hardbreak. That said, users are _already_ choosing when introducing documents in Markdown format, leading to the very bug reports that we're seeing here. :)

An even nicer fix would, IMO, be to render the hardbreak correctly for the context it's in. This would require peeking ahead while rendering, and to be frank I haven't thought about it clearly enough to know if it's a sensible suggestion.

**Comment by jneem** [comment]
Makes sense, I'll give that a try. I *think* either of the following behaviors would be correct:
1. render spaces unless at the beginning of a block
2. render a backslash unless at the end of a block

The first one sounds easier to me since it doesn't require look-ahead. I'll try to implement it soon.
