### ISSUE TITLE
Exclamation before a footnote gets eaten

### ISSUE THREAD

**Issue by kivikakk** [kivikakk/comrak#43]
Same as https://github.com/github/cmark/issues/66.

```shell
~/kivikakk/comrak master$ target/debug/comrak --footnotes <<EOT
> Hi![^hi]
>
> [^hi]: OK.
> EOT
<p>Hi<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></p>
<section class="footnotes">
<ol>
<li id="fn1">
<p>OK. <a href="#fnref1" class="footnote-backref">↩</a></p>
</li>
</ol>
</section>
```

**Comment by SSJohns** [comment]
Hey, I ran into a similar thing and the big problem was because it was streaming so it didn't check if the lines in question were prescribed to one set or another. In this case I'd suggest some kind of check as to weather this was a valid image `![foo](/bar)` in https://github.com/kivikakk/comrak/blob/master/src/parser/inlines.rs#L128-L132. 

Either
```
if self.peek_char() == Some(&(b'[')) && self.peek_char(2) != Some(&(b"^")) {
  self.pos += 1;
  let inl = make_inline(self.arena, NodeValue::Text(b"![".to_vec()));
  new_inl = Some(inl);
  self.push_bracket(true, inl);
}
```
Where you would have to implement a peek_char that can look n ahead. I assume anytime there are brackets you want the `^` at the beginning to indicate a footnote right? In that case this might work. Let me know what you think.

**Comment by kivikakk** [comment]
Yep, this works nicely! Thank you so much!
