### ISSUE TITLE
How to preprocess markdown?

### ISSUE THREAD

**Issue by GildedHonour** [kivikakk/comrak#85]
Say, I have a tag audio, video, image or whatever and I want to dynamically adjust it's "source" before rendering it on an html page.   Does comrak provide an api for an element to do so?

**Comment by kivikakk** [comment]
You can walk the returned AST until you find the `InlineHtml` or `BlockHtml` representing the tag in question. It doesn't parse HTML — that's a non-goal of CommonMark — so you'll still have quite a bit of work to do.

**Comment by GildedHonour** [comment]
thx

does the library support <audio ... and <video markdown tags?

**Comment by kivikakk** [comment]
No problem!

And unfortunately not; there’s no syntax in CommonMark for those tags, nor any extension implemented.

**Comment by GildedHonour** [comment]
If I want to extend it for myself, something like this:

   [audio](/path/file.mp4)

which will be parsed into the real audio tag, how will I add that tag? Is there a similar example in the library?

**Comment by brson** [comment]
@GildedHonour my downstream branch does something like that, commandeering the image syntax like `![video](<hashcode>)` (we use hash identifiers instead of paths. I can't share the full code off hand, but here's a snippet:

https://gist.github.com/brson/b180839aa4a236bc78e7b86eca3f7877

I'm not saying this is the cleanest way to do it, but it's what we do - note that when we're in our custom mode, indicated by the 'rtjson' flag - we use a totally new AST node, NodeMeda, to indicate it's special. Elsewhere we have further validation that the text of that node is 'video', 'image', 'gif', etc. - Depending on your needs you might check for those 'keywords' right there to make the decision to use the custom node.

From there you just have to edit html.rs, which should be pretty obvious since it's a small repetitive file.

Hope that helps.

**Comment by GildedHonour** [comment]
@brson Thanks. But I can't understand how that can be useful for my case because that's quite a small part of code. Can you share more?

Also, there's "}" missing in the very end, or somewhere else.

**Comment by brson** [comment]
@GildedHonour sorry for the lack of detail. I meant to give a hint of a reasonable place to reinterpret the link syntax. The rest I'd expect to fall out of that via compiler errors.

In `close_bracket_match` (the function to finish a successfully parsed link) you can use logic to, instead of creating a `NodeLink`, create your own custom node (like my `NodeMedia`), perhaps when `url` equals "audio". You'll need to add the new node in `nodes.rs'. From there you can extend the renderer in `html.rs` to emit the audio tag (and maybe the one in `cm.rs`). That's about all that's needed, afaicr offhand.

Another way to do it is to have an AST post-processing pass that walks the AST and looks for `NodeLink` and changes them as appropriate to `NodeMedia`. Cleaner but slower.

**Comment by GildedHonour** [comment]
@brson yes, I can. That's why I asked for more code.

**Comment by kivikakk** [comment]
I'll close this issue out now; thanks @brson for dropping in with pointers from your own work!
